name: Release
on:
  push:
    branches:
      - main

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: access_token
          workload_identity_provider: "projects/<project-id>/locations/global/workloadIdentityPools/<workload-identity-pool-name>/providers/<workload-identity-provider-name>"
          service_account: "<service-account-name>@<project-id>.iam.gserviceaccount.com"
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-docker.pkg.dev/
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: docker-push-tagged
        name: Tag Atlantis Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            ATLANTIS_GH_USER=${{ secrets.ATLANTIS_GH_USER }}
            ATLANTIS_GH_TOKEN=${{ secrets.ATLANTIS_GH_TOKEN }}
            ATLANTIS_GH_WEBHOOK_SECRET=${{ secrets.ATLANTIS_GH_WEBHOOK_SECRET }}
          tags: |
            <region>-docker.pkg.dev/<project-id>/<repo-name>/<docker-image-name>:<tag>

